require 'csv'

Episode.delete_all
Movie.delete_all

CSV.open('episodes.csv').each do |r|
  m = Movie.find_or_create_by(imdb_id: r[1], letterboxd_id: r[2]) if r[1].present?
  if m
    Episode.find_or_create_by(id: r[0], movie: m)
  else
    Episode.find_or_create_by(id: r[0])
  end
end

Host.delete_all
Host.create(id: 1, name: 'Dan McCoy')
Host.create(id: 2, name: 'Stuart Wellington')
Host.create(id: 3, name: 'Elliott Kalan')
Host.create(id: 4, name: 'Hallie Haglund')
Host.create(id: 5, name: 'Zhubin Parang')
Host.create(id: 6, name: 'Al Madrigal')
Host.create(id: 7, name: 'Tom Silvestro')
Host.create(id: 8, name: 'Wyatt Cenac')
Host.create(id: 9, name: 'Andy Rocco')
Host.create(id: 10, name: 'Lou Fernandez')
Host.create(id: 11, name: 'John Kingman')
Host.create(id: 12, name: 'Federico Hatoum')
Host.create(id: 13, name: 'Brock Mahan')
Host.create(id: 14, name: 'Eric Zuckerman')
Host.create(id: 15, name: 'Amanda Melson')
Host.create(id: 16, name: 'Matt Koff')
Host.create(id: 17, name: 'Nigel Wood')
Host.create(id: 18, name: 'Dash Coombs')
Host.create(id: 19, name: 'Bob Powers')
Host.create(id: 20, name: 'Meghan O\'Neill')
Host.create(id: 21, name: 'Will Hines')
Host.create(id: 22, name: 'Ritch Duncan')
Host.create(id: 23, name: 'Sara Schaefer')
Host.create(id: 24, name: 'Frank Lesser')
Host.create(id: 25, name: 'Jeanette Lahr')
Host.create(id: 26, name: 'Simon Fisher')
Host.create(id: 27, name: 'Jessica Williams')
Host.create(id: 28, name: 'Kevin Maher')
Host.create(id: 29, name: 'Jordan Morris')
Host.create(id: 30, name: 'David Kalan')
Host.create(id: 31, name: 'John Hodgman')
Host.create(id: 32, name: 'Paul Sabourin')
Host.create(id: 33, name: 'Travis McElroy')
Host.create(id: 34, name: 'April Wolfe')
Host.create(id: 35, name: 'Joe Bob Briggs')
Host.create(id: 36, name: 'Jenny Jaffe')
Host.create(id: 37, name: 'Natalie Walker')
Host.create(id: 38, name: 'Sharlene Wellington')
Host.create(id: 39, name: 'Brendan Hay')
Host.create(id: 40, name: 'Adal Rifai')
Host.create(id: 41, name: 'Griffin Newman')
Host.create(id: 42, name: 'Chris Weitz')
Host.create(id: 43, name: 'Jamelle Bouie')
Host.create(id: 44, name: 'David Sims')
Host.create(id: 45, name: 'Jordan Kauwling')
Host.create(id: 46, name: 'Erin Foley-Chan')
Host.create(id: 47, name: 'Scott Weinberg')
Host.create(id: 48, name: 'Roman Mars')
Host.create(id: 49, name: 'Jesse Thorn')
Host.create(id: 50, name: 'Gillian Flynn')
Host.create(id: 51, name: 'Annabelle Gurwitch')
Host.create(id: 52, name: 'Justin McElroy')
Host.create(id: 53, name: 'Alonso Duralde')
Host.create(id: 54, name: 'Josh Gondelman')
Host.create(id: 55, name: 'Arnie Niekamp')
Host.create(id: 56, name: 'Glen Weldon')
Host.create(id: 57, name: 'Zander Cannon')
