#!/bin/sh

# script/_lint: Run our code linters
# This should be run within the docker container, not on your on laptop


set -e

cd "$(dirname "$0")/.."

echo "==> Database backup..."
sqlite3 db/development.sqlite3 .dump > db/development.sql
