#!/bin/bash

# script/add_episode: Runs the rake task to add the latest episode

set -e

cd "$(dirname "$0")/.."

docker run \
  --rm \
  -it \
  --env-file .env \
  -e RAILS_ENV=development \
  -v "$PWD":/rails \
  fhr:latest \
  ./bin/rails episode:add
