#!/bin/bash

# script/autoformat: Autoformats all Ruby code or the single provided file

set -e

cd "$(dirname "$0")/.."

docker run \
  --rm \
  -it \
  -v "$PWD":/app \
  --env-file .env \
  --entrypoint standardrb \
  fhr:latest
