#!/bin/bash

# script/setup: Tells Docker to setup the project by configuring YAML config files
# & getting and building Docker images.

set -e

cd "$(dirname "$0")/.."

docker build --platform linux/amd64 -t fhr:latest .
docker tag fhr:latest registry.heroku.com/afternoon-hollows-06212/web
docker push registry.heroku.com/afternoon-hollows-06212/web
heroku container:release web -a afternoon-hollows-06212
