#!/bin/bash

# script/setup: Tells Docker to setup the project by configuring YAML config files
# & getting and building Docker images.

set -e

cd "$(dirname "$0")/.."

echo "==> Getting/Building Docker images"
docker build -t fhr:latest .

echo "==> Creating a pre-commit hook"
cp script/hooks/* .git/hooks

echo "==> All done!"
